class App{
    //コンストラクタ
    constructor(){
        this.eventHandlers= [];
        this.intervals    = [];

        //ページのロードが完了した時
        window.addEventListener('load',()=>{
            this.title();
        });
    }

    //タイトル
    title(){
        //すべてのイベントハンドラーを解除
        if(this.eventHandlers.length){
            for(let i=-0; i<this.eventHandlers.length;i++){
                if(this.eventHandlers[i])document.removeEventListener(this.eventHandlers[i].typename,this.eventHandlers[i].callback);
            }
            this.eventHandlers=[];
        }
        //UIを構築し描画
        let titleElement        =   '<div class="title"><h1>タイピングゲーム</h1><button onclick="app.playTypingGame();">ゲーム開始</button></div>';
        let containerElement    = '<div class="container">${titleElement}</div>';
        let mainElement         = '<main>${containerElement}</main>';

        document.querySelector('body').innerHTML=mainElement;

        return true;
    }

    //タイピングゲームの準備
    playTypingGame(){
        //タイピングゲームのデータがない場合、出題データファイルをフェッチして自分をコールバックする
        if(!this.typingGame_deta){
            this.typingGame_deta={
                questionContents:[
                    {
                        "string":"吾輩は猫である",
                        "characters":[
                            {
                                "text":"吾",
                                "hiragana":"わが",
                                "katakana":"ワガ",
                                "romaji":"waga"
                            },
                            { 
                                "text":"輩",
                                "hiragana":"はい",
                                "katakana":"ハイ",
                                "romaji":"hai" 
                            },
                            {
                                "text":"は",
                                "hiragana":"は",
                                "katakana":"ハ",
                                "romaji":"ha"
                            },
                            {
                                "text":"猫",
                                "hiragana":"ねこ",
                                "katakana":"ネコ",
                                "romaji":"neko"
                            },
                            {
                                "text":"で",
                                "hiragana":"で",
                                "katakana":"デ",
                                "romaji":"de"
                            },
                            {
                                "text":"あ",
                                "hiragana":"あ",
                                "katakana":"ア",
                                "romaji":"a"
                            },
                            {
                                "text":"る",
                                "hiragana":"る",
                                "katakana":"ル",
                                "romaji":"ru"
                            }
                        ]
                    },
                    {
                     "string":"雨二モマケズ風ニモマケズ" ,
                     "characters":  [ 
                    {
                        "text":"雨",
                        "hiragana":"あめ",
                        "katakana":"アメ",
                        "romaji":"ame"
                    },
                    {
                        "text":"二",
                        "hiragana":"に",
                        "katakana":"二",
                        "romaji":"ni"
                    },
                    {
                        "text":"モ",
                        "hiragana":"も",
                        "katakana":"モ",
                        "romaji":"mo"
                    },
                    {
                        "text":"マ",
                        "hiragana":"ま",
                        "katakana":"マ",
                        "romaji":"ma"
                    },
                    {
                        "text":"ケ",
                        "hiragana":"け",
                        "katakana":"ケ",
                        "romaji":"ke"
                    },
                    {
                        "text":"ズ",
                        "hiragana":"ず",
                        "katakana":"ズ",
                        "romaji":"zu"
                    },
                    {
                        "text":"風",
                        "hiragana":"かぜ",
                        "katakana":"カゼ",
                        "romaji":"kaze"
                    },
                    {
                        "text":"二",
                        "hiragana":"に",
                        "katakana":"二",
                        "romaji":"ni"
                    },
                    {
                        "text":"モ",
                        "hiragana":"も",
                        "katakana":"モ",
                        "romaji":"mo"
                    },
                    {
                        "text":"マ",
                        "hiragana":"ま",
                        "katakana":"マ",
                        "romaji":"ma"
                    },
                    {
                        "text":"ケ",
                        "hiragana":"け",
                        "katakana":"ケ",
                        "romaji":"ke"
                    },
                    {
                        "text":"ズ",
                        "hiragana":"ず",
                        "katakana":"ズ",
                        "romaji":"zu"
                    }
                ]       
            },
            {
              "string":"こんにちは、世界！",
              "characters":[
                 {
                            "text":"こ",
                            "hiragana":"こ",
                            "katakana":"コ",
                            "romaji":"ko"
                        },
                        {
                            "text":"ん",
                            "hiragana":"ん",
                            "katakana":"ン",
                            "romaji":"nn"
                        },
                        {
                            "text":"に",
                            "hiragana":"に",
                            "katakana":"二",
                            "romaji":"ni"
                        },
                        {
                            "text":"ち",
                            "hiragana":"ち",
                            "katakana":"チ",
                            "romaji":"ti"
                        },
                        {
                            "text":"は",
                            "hiragana":"は",
                            "katakana":"ハ",
                            "romaji":"ha"
                        },
                        {
                            "text":"、",
                            "hiragana":"、",
                            "katakana":"、",
                            "romaji":","
                        },
                        {
                            "text":"世",
                            "hiragana":"せ",
                            "katakana":"セ",
                            "romaji":"se"
                        },
                        {
                            "text":"界",
                            "hiragana":"かい",
                            "katakana":"かい",
                            "romaji":"kai"
                        },
                        {
                            "text":"!",
                            "hiragana":"!",
                            "katakana":"!",
                            "romaji":"!"
                        }     
                    ]  
                },
                {
                    "string":"早起きは三文の徳",
                    "characters":[
                       {
                                  "text":"早",
                                  "hiragana":"はや",
                                  "katakana":"ハヤ",
                                  "romaji":"haya"
                              },
                              {
                                  "text":"起",
                                  "hiragana":"お",
                                  "katakana":"オ",
                                  "romaji":"o"
                              },
                              {
                                  "text":"き",
                                  "hiragana":"き",
                                  "katakana":"キ",
                                  "romaji":"ki"
                              },
                              {
                                  "text":"は",
                                  "hiragana":"は",
                                  "katakana":"ハ",
                                  "romaji":"ha"
                              },
                              {
                                  "text":"三",
                                  "hiragana":"さん",
                                  "katakana":"サン",
                                  "romaji":"sann"
                              },
                              {
                                  "text":"文",
                                  "hiragana":"もん",
                                  "katakana":"モン",
                                  "romaji":"monn"
                              },
                              {
                                  "text":"の",
                                  "hiragana":"の",
                                  "katakana":"ノ",
                                  "romaji":"no"
                              },
                              {
                                  "text":"徳",
                                  "hiragana":"とく",
                                  "katakana":"トク",
                                  "romaji":"toku"
                              }
                               
                            ]
                        },
                        {
                            "string":"こんにちは、今日は良い天気ですね",
                            "characters":[
                               {
                                          "text":"こ",
                                          "hiragana":"こ",
                                          "katakana":"コ",
                                          "romaji":"ko"
                                      },
                                      {
                                          "text":"ん",
                                          "hiragana":"ん",
                                          "katakana":"ン",
                                          "romaji":"nn"
                                      },
                                      {
                                          "text":"に",
                                          "hiragana":"に",
                                          "katakana":"二",
                                          "romaji":"ni"
                                      },
                                      {
                                          "text":"ち",
                                          "hiragana":"ち",
                                          "katakana":"チ",
                                          "romaji":"ti"
                                      },
                                      {
                                          "text":"は",
                                          "hiragana":"は",
                                          "katakana":"ハ",
                                          "romaji":"ha"
                                      },
                                      {
                                          "text":"、",
                                          "hiragana":"、",
                                          "katakana":"、",
                                          "romaji":","
                                      },
                                      {
                                          "text":"今日",
                                          "hiragana":"きょう",
                                          "katakana":"キョウ",
                                          "romaji":"kyou"
                                      },
                                      {
                                          "text":"は",
                                          "hiragana":"は",
                                          "katakana":"ハ",
                                          "romaji":"ha"
                                      },
                                      {
                                          "text":"良",
                                          "hiragana":"い",
                                          "katakana":"イ",
                                          "romaji":"i"
                                      },
                                      {
                                        "text":"い",
                                        "hiragana":"い",
                                        "katakana":"イ",
                                        "romaji":"i"
                                    },
                                    {
                                        "text":"天",
                                        "hiragana":"てん",
                                        "katakana":"テン",
                                        "romaji":"tenn"
                                    },
                                    {
                                        "text":"気",
                                        "hiragana":"き",
                                        "katakana":"キ",
                                        "romaji":"ki"
                                    },
                                    {
                                        "text":"で",
                                        "hiragana":"で",
                                        "katakana":"デ",
                                        "romaji":"de"
                                    },
                                    {
                                        "text":"す",
                                        "hiragana":"す",
                                        "katakana":"ス",
                                        "romaji":"su"
                                    },
                                    {
                                        "text":"ね",
                                        "hiragana":"ね",
                                        "katakana":"ネ",
                                        "romaji":"ne"
                                    }
                                ]
                            }
                
                ]
       };
       return this.playTypingGame();
    }
    
    let typeGameElement        =   '<div class="typeGame"><div class="time">00:00:00</div><h2></h2><p>Entarキーを押すとゲームが始まります。</p><button onClick="app.title();">やめる</button></div>';
    let containerElement    = '<div class="container">${typeGameElement}</div>';
    let mainElement         = '<main>${containerElement}</main>';

    document.querySelector('body').innerHTML=mainElement;

    //キー入力イベントリスナーを追加
    let eventHandler={
        typeName:'Keydown',
        callback: event=>{
            if(event.Key==='Enter'){
                this.typingGame_deta=[0,0,0];

                this.typingGame_deta.typingCount=0;
                this.typingGame_deta.missCount=0;
                this.typingGame_deta.clearCount=0;

                this.typingGame_deta.currentQuestionIndex=0;
                this.typingGame_deta.mustEnteredKeys=[];

                this.startTypingGame();
            }
        }
    };
    this.eventHandlers[0]=eventHandler;
    document.addEventListener(eventHandler.typeName,eventHandler.callback);

    return true;
}

//タイピングゲームを開始
startTypingGame(){
    //すべてのイベントハンドラーを解除
    if(this.eventHandlers.length){
        for(let i=0;i<this.eventHandlers.length;i++){
            document.removeEventListener(this.eventHandlers[i].typeName,this.eventHandlers[i].callback);
        }
        this.eventHandlers=[];
    }

    //問題確認関数定義
    let generateMustEnteredKey=()=>{
        if(!this.typingGame_deta.questionContents) return false;

        let questionContent=this.typingGame_deta.questionContents[this.typingGame_deta.]
    }
}
}

